### ISSUE TITLE
Cant create conference

### ISSUE THREAD

**Issue by jncraig** [DNN-Connect/Conference#2]
Installed module in new DNN8 installation.

Installed module on a page and tried to create a New Conference.  Clicking "Save" results in nothing happening and no meaningful errors logged.  There is a "module updated" logged, but nothing in it.

No conference was created.

**Comment by donker** [comment]
Hey Joe! First ensure you're on the very last version (I just uploaded 2.0.7). Then: check with Fiddler to see if the button click even proked some kind of traffic with the server or not. If not then there is some JS problem. If there is, then maybe the issue is somewhere else.

**Comment by donker** [comment]
It could actually be related to the date format. There is a check for it. But with Javascript and dates all kinds of things can happen. If you open the console does it give you an error message as you click Submit?

**Comment by jncraig** [comment]
Peter,

I installed 2.0.7.

The problem persists.

When I click the "New Conference" button, I get this:

#ResultProtocolHostURLBodyCachingContent-TypeProcessCommentsCustom
162 200 HTTP dnncon.patapscoresearch.com
/Conference/moduleId/484/conferenceId/-1/controller/Conference/action/Edit
20,447 no-cache; Expires: -1 text/html; charset=utf-8 chrome:26916
163 200 HTTP dnncon.patapscoresearch.com
/DnnImageHandler.ashx?mode=profilepic&userId=1&h=32&w=32 8,192 private
image/jpeg chrome:26916
164 404 HTTP dnncon.patapscoresearch.com
/DesktopModules/MVC/Connect/Conference/js/interact.min.js.map 1,125
text/html chrome:26916

When I click the "Save" button to create the new conference, I see:

#ResultProtocolHostURLBodyCachingContent-TypeProcessCommentsCustom
39 302 HTTP dnncon.patapscoresearch.com
/Conference/moduleId/484/conferenceId/-1/controller/Conference/action/Edit
71,328 no-cache; Expires: -1 text/html; charset=utf-8 chrome:26916
40 200 HTTP dnncon.patapscoresearch.com /Conference 19,463 no-cache;
Expires: -1 text/html; charset=utf-8 chrome:26916
41 200 HTTP dnncon.patapscoresearch.com
/DnnImageHandler.ashx?mode=profilepic&userId=1&h=32&w=32 8,192 private
image/jpeg chrome:26916

**Comment by donker** [comment]
Hi Joe,

Did you fill in dates? Did that work? What is the date format?

Second question: have you tried opening up the console and seeing if any errors are happening in JS? This is the downside of our new way of development: lots more stuff happening client-side that is harder to trace.

Best,

Peter

PS if you’re setting this up for DNNCON I’d be happy to sink some hours myself as well in setting it up if you wish.

**Comment by jncraig** [comment]
Sorry, I guess I left that part out.

I entered the dates using the date picker.

No errors shown in the console.
